CREATE TABLE IF NOT EXISTS `mst_risk_impact_indicators` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(50) DEFAULT NULL,
  `name` varchar(250) DEFAULT NULL,
  `mst_risk_impact_category_id` int(10) NOT NULL,
  `indicator_A` text NULL,
  `indicator_B` text NULL,
  `indicator_C` text NULL,
  `indicator_D` text NULL,
  `indicator_E` text NULL,
  `mst_risk_impact_id_A` int(10) NULL,
  `mst_risk_impact_id_B` int(10) NULL,
  `mst_risk_impact_id_C` int(10) NULL,
  `mst_risk_impact_id_D` int(10) NULL,
  `mst_risk_impact_id_E` int(10) NULL,
  `description` text NULL,
  `status` int(2) NOT NULL DEFAULT '1',
  `unit_id` int(10) DEFAULT NULL,
  `created_by` int(20) NOT NULL,
  `created_date` datetime NOT NULL,
  `updated_by` int(20) DEFAULT NULL,
  `updated_date` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;