ALTER TABLE `tx_key_risk_indicator` ADD COLUMN `HAZARD` TEXT NULL AFTER `RISK_ITEM_ID`;
ALTER TABLE `tx_key_risk_indicator` ADD COLUMN `DASHBOARD_DESCRIPTION` TEXT NULL AFTER `HAZARD`;
ALTER TABLE `tx_key_risk_indicator` ADD COLUMN `THRESHOLD_VALUE` DECIMAL(25,2) NULL AFTER `DASHBOARD_DESCRIPTION`;
ALTER TABLE `tx_key_risk_indicator` ADD COLUMN `TOP_RISK_NUMBER` INT(25) NULL AFTER `THRESHOLD_VALUE`;
ALTER TABLE `tx_key_risk_indicator` ADD COLUMN `BASIC_EVENT` TEXT NULL AFTER `HAZARD`;
ALTER TABLE `tx_key_risk_indicator` ADD COLUMN `key_risk_indicator_threshold_id` INT(25) NULL AFTER `DASHBOARD_DESCRIPTION`;
ALTER TABLE `tx_key_risk_indicator` ADD COLUMN `risk_kpi_id` INT(25) NULL AFTER `CODE`;