ALTER TABLE `tx_risk_mitigation` ADD COLUMN `DAMPAK_RENCANA_PENGENDALIAN` mediumtext NULL AFTER `RENCANA_PENGENDALIAN`;
ALTER TABLE `tx_risk_mitigation` ADD COLUMN `MULAI_WAKTU` date NULL AFTER `PIC_KANTOR_PUSAT_ID`;
ALTER TABLE `tx_risk_mitigation` ADD COLUMN `MITIGATION_COSTS` DECIMAL(15,2) NULL AFTER `TARGET_WAKTU`;
ALTER TABLE `tx_risk_mitigation` MODIFY `PIC_UNIT_KERJA_ID` int(11) NULL;
ALTER TABLE `tx_risk_mitigation` MODIFY `PIC_KANTOR_PUSAT_ID` int(11) NULL;
ALTER TABLE `tx_risk_mitigation` ADD COLUMN `EXECUTION_TIME` date NULL AFTER `REALISASI_MITIGASI`;
ALTER TABLE `tx_risk_mitigation` ADD COLUMN `YEAR` varchar(4) NULL AFTER `EXECUTION_TIME`;
ALTER TABLE `tx_risk_mitigation` ADD COLUMN `MONTH` varchar(2) NULL AFTER `YEAR`;
ALTER TABLE `tx_risk_mitigation` ADD COLUMN `DAY` varchar(2) NULL AFTER `MONTH`;
